version: '3.1'

services:

  web-client:
    image: nginx
    volumes:
    - ./web-client:/usr/share/nginx/html
    ports:
    - "8083:80"
  web-client-ngrok:
    image: wernight/ngrok
    restart: always
    ports:
      - 4043:4040
    environment:
      NGROK_PORT: 'web-client:80'
  web-api:
    build:
      context: ./web-api
    ports:
    - "8084:3000"
    volumes:
      - ./web-api:/usr/src/app/
    command: /usr/src/app/entrypoint.sh
    depends_on:
      - db-cli
    restart: always
  web-api-ngrok:
    image: wernight/ngrok
    restart: always
    ports:
      - 4044:4040
    environment:
      NGROK_PORT: 'web-api:3000'
    depends_on:
      - web-api
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql/data
  db-cli:
    image: mariadb
    depends_on:
      - db
    command: mysql -h db -u root --password=example -e "CREATE DATABASE IF NOT EXISTS cual_curso;"
    restart: on-failure
  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080
    depends_on:
      - db
  adminer-ngrok:
    image: wernight/ngrok
    restart: always
    ports:
      - 4046:4040
    environment:
      NGROK_PORT: 'adminer:8080'
    depends_on:
      - adminer

volumes:
  db-data:
