version: '3.1'

services:

  web-spa:
    image: node:10
    working_dir: /usr/src/app
    command: npm start
    ports:
    - "3002:3000"
    volumes:
      - ./web-spa:/usr/src/app
    restart: always

  web-client:
    image: nginx
    volumes:
    - ./web-client:/usr/share/nginx/html
    ports:
    - "81:80"
  web-api:
    image: node:10
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3001:3000"
    volumes:
      - ./web-api:/usr/src/app/
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: mi-pass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  db-data:
